apiVersion: v1
kind: Service
metadata:
  name: {{ include "existdb.fullname" . }}
  labels:
    {{- include "existdb.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    {{- include "existdb.selectorLabels" . | nindent 4 }}
