on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: redhat-actions/podman-login@v1
    - uses: redhat-actions/buildah-build@v2
    - if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      uses: redhat-actions/push-to-registry@v2
